vich_uploader:
    db_driver: orm

    mappings:
        creations:
            uri_prefix: '%creation_images%'
            upload_destination: '%kernel.project_dir%/public%creation_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
